<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo reference="base_link">
        <material>Gazebo/SkyBlue</material>
	    <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="base_scan">
        <material>Gazebo/Grey</material>
	    <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="uwb_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <xacro:macro name="wheel_transmission" params="name">
        <gazebo reference="wheel_${name}_link">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="10000000.0"/>
            <kd value="1.0"/>
            <fdir1 value="0.2"/>
            <material>Gazebo/Black</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <!-- <transmission name="wheel_${name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="wheel_${name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="wheel_${name}_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission> -->
    </xacro:macro>
    
    <!-- <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <legacyMode>false</legacyMode>
            <updateRate>100</updateRate>
            <leftJoint>wheel_front_left_joint</leftJoint>
            <rightJoint>wheel_front_right_joint</rightJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <wheelTorque>5</wheelTorque>
            <torque>5</torque>
            <commandTopic>/my_robot/cmd_vel</commandTopic>
            <odometryTopic>odom_gazebo</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometrySource >encoder</odometrySource >
            <publishOdomTF>false</publishOdomTF>
            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>false</publishWheelJointState>
            <publishTf>1</publishTf>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <wheelAcceleration>0</wheelAcceleration>
            <rosDebugLevel>na</rosDebugLevel>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <legacyMode>false</legacyMode>
            <updateRate>100</updateRate>
            <leftJoint>wheel_rear_left_joint</leftJoint>
            <rightJoint>wheel_rear_right_joint</rightJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <wheelTorque>5</wheelTorque>
            <torque>5</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom_gazebo</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometrySource >encoder</odometrySource >
            <publishOdomTF>false</publishOdomTF>
            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>false</publishWheelJointState>
            <publishTf>1</publishTf>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <wheelAcceleration>0</wheelAcceleration>
            <rosDebugLevel>na</rosDebugLevel>
        </plugin>
    </gazebo> -->

    <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <leftFrontJoint>wheel_front_left_joint</leftFrontJoint>
            <rightFrontJoint>wheel_front_right_joint</rightFrontJoint>
            <leftRearJoint>wheel_rear_left_joint</leftRearJoint>
            <rightRearJoint>wheel_rear_right_joint</rightRearJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <robotBaseFrame>base_link</robotBaseFrame>
            <torque>5</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom_gazebo</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <wheelAcceleration>0</wheelAcceleration>
            <rosDebugLevel>na</rosDebugLevel>
            <covariance_x>0.001</covariance_x>
            <covariance_y>0.001</covariance_y>
            <covariance_yaw>0.01</covariance_yaw>
            <broadcastTF>false</broadcastTF>
        </plugin>
    </gazebo>

    <gazebo reference="base_scan">
        <sensor type="ray" name="lidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>100</update_rate>
            <ray>
                <scan>
                    <horizontal>
                    <samples>2000</samples>
                    <resolution>1</resolution>
                    <min_angle>-${PI}</min_angle>
                    <max_angle>${PI}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.15</min>
                    <max>12.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/my_robot/scan</topicName>
                <frameName>base_scan</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo reference="imu_link">
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>/my_robot/imu</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>/my_robot/imu</topicName>
                <bodyName>imu_link</bodyName>
                <updateRateHZ>50.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu_link</frameName>
                <initialOrientationAsReference>false</initialOrientationAsReference>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin name='libgtec_uwb_plugin' filename='libgtec_uwb_plugin.so'>
            <update_rate>100</update_rate>
            <nlosSoftWallWidth>0.25</nlosSoftWallWidth>
            <tag_z_offset>0</tag_z_offset>
            <tag_link>tag_0</tag_link>
            <anchor_prefix>uwb_anchor</anchor_prefix>
            <all_los>false</all_los>
            <tag_id>0</tag_id>
        </plugin>
    </gazebo>

    <gazebo> 
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/my_robot</robotNamespace>
            <controlPeriod>0.001</controlPeriod>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType> 
            <legacyModeNS>true</legacyModeNS> 
        </plugin> 
    </gazebo>
    
</robot>