diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50

  left_wheel: ['wheel_front_left_joint', 'wheel_rear_left_joint']
  right_wheel: ['wheel_front_right_joint', 'wheel_rear_right_joint']

  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

  wheel_separation: 0.33
  wheel_radius: 0.075  
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  cmd_vel_timeout: 0.25
  enable_odom_tf: false
  base_frame_id: base_footprint

  # Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3   # rad/s^2